### ISSUE TITLE
android.os.NetworkOnMainThreadException when closing.

### ISSUE THREAD

**Issue by dsuresh-ap** [launchdarkly/okhttp-eventsource#54]
Calling `EventSource.close()` throws an `android.os.NetworkOnMainThreadException`

This call should have its internal logic that requires the network be on a background thread or update the docs to note that calling `close()` requires a background thread.

```
2020-09-17 13:33:34.255 20876-20876/com.E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com., PID: 20876
    java.lang.RuntimeException: Unable to resume activity {com.}: android.os.NetworkOnMainThreadException
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
        at com.google.android.gms.org.conscrypt.Platform.blockGuardOnNetwork(:com.google.android.gms@203019040@20.30.19 (120700-326531024):0)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.shutdownAndFreeSslNative(:com.google.android.gms@203019040@20.30.19 (120700-326531024):1)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.close(:com.google.android.gms@203019040@20.30.19 (120700-326531024):9)
        at okhttp3.internal.Util.closeQuietly(Util.java:154)
        at okhttp3.internal.connection.RealConnectionPool.evictAll(RealConnectionPool.java:154)
        at okhttp3.ConnectionPool.evictAll(ConnectionPool.java:55)
        at com.launchdarkly.eventsource.EventSource.close(EventSource.java:212)
```

**Comment by gwhelanLD** [comment]
I've filed internally (ch91466) for us to update the comment to include that `close()` performs network actions on the calling thread.

Thanks,
@gwhelanLD

**Comment by eli-darkly** [comment]
Unfortunately this fell through the cracks and we didn't notice this lingering issue prior to the 4.0.0 release, but we have finally updated the doc comments so at least they will mention this issue in the _next_ release.
